@startuml

!theme plain
skinparam DefaultFontName Monospaced

title Connection via Wi-Fi in Local networks

entity Node_1
entity Node_2
entity Node_3
entity MasterNode

=== Reg-in to the system ==

Node_1 -> MasterNode: Broadcast: I'm here, no last update
MasterNode -> MasterNode: Adds IP to table
activate Node_1
activate MasterNode

MasterNode -> Node_1: [TCP CONNECT] Ya're new, Solider! Your stats?
Node_1 -> MasterNode: No assets, Sir!
MasterNode ->(30) Node_1: Take your assets.
Node_1 --> MasterNode: ACK! [CONNECTION IS CLOSED]

deactivate Node_1
deactivate MasterNode

Node_1 -> Node_1: Initializing code & assets.


Node_1 -> Node_2: Broadcast: I'm here
Node_2 -> Node_2: Adds IP to table

Node_1 -[#red,dashed]> Node_3: Broadcast: I'm here [DATAGRAM IS LOST] 

Node_3 -> Node_3: Adds IP to table

Node_2 -> Node_1: Unicast: Chunk sync part
Node_1 -> Node_1: Adds IP to table
Node_1 -> Node_1: EMA to weights

Node_2 -> Node_3: Unicast: Chunk part
Node_3 -> Node_2: EMA to weights

Node_2 -> MasterNode: Unicast: Chunk part
MasterNode -> MasterNode: EMA to weights


Node_3 -> Node_2: Unicast: Chunk sync part
Node_2 -> Node_2: EMA to weights

Node_3 -> MasterNode: Unicast: Chunk sync part
MasterNode -> MasterNode: EMA to weights

MasterNode -> Node_1: Unicast: Chunk sync part
Node_1 -> Node_1: Adds IP to table

=== After 30 seconds ==

Node_3 -> Node_1: Broadcast: I'm here
Node_1 -> Node_1: Adds IP to table
Node_3 -> Node_2: Broadcast: I'm here
Node_2 -> Node_2: Updates last\nIP occurance TimeStamp
Node_3 -> MasterNode: Broadcast: I'm here last udpdate\nI've received at XXX

MasterNode -> MasterNode: Updates last\nIP occurance TimeStamp
MasterNode -> MasterNode: Checks how frequently this IP receives updates\n& seems this frequency is OK [NOTHING TO DO]
& note over MasterNode
H
end note
note over Node_2

This node seems to be lost
for a while...

end note

== ... ==

@enduml
